version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:stable

jobs:
  flow:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
    working_directory: ~/monorepo
    steps:
      - run: mkdir -p sdk/iphone/local/ 
      - run: echo "Hello, world!" > sdk/iphone/local/echo-output
      - run: |
          dd if=/dev/urandom of=randomfile bs=10M count=1 
          zip sdk/iphone/local/randomfile.zip randomfile
          zip sdk/iphone/local/randomfile-1.zip randomfile
          zip sdk/iphone/local/randomfile-aa.zip randomfile
          zip sdk/iphone/local/randomfile-bb.zip randomfile
      - persist_to_workspace:
          root: .
          paths:
            - echo-output
            - sdk/iphone/local/*.zip

  downstream:
    executor: my-executor
    working_directory: ~/monorepo
    steps:
      - attach_workspace:
          at: ./
      - run: |
          if [[ `cat monorepo/sdk/iphone/local/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
      - run: echo "export OUTPUT='$(cat echo-output)'" >> "$BASH_ENV"
      - run: echo $OUTPUT
      - run: ls -la monorepo/sdk/iphone/local

workflows:
  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
